---
name: create-pr

on:
  workflow_dispatch:
  schedule:
    # This should conincide with the Konflux maintence window.
    # This is currently Friday at 1AM-3AM UTC or 10AM-2PM UTC
    - cron: '0 10 * * 5'

permissions:
  contents: read

jobs:
  create-infra-deployments-pr:
    runs-on: ubuntu-latest

    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
      with:
        egress-policy: audit
        disable-telemetry: true

    - name: Checkout infra-deployments
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        repository: redhat-appstudio/infra-deployments
        ref: main
        path: infra-deployments

    - name: Checkout ec
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        repository: conforma/cli
        ref: main
        path: cli

    - name: Update ec
      run: ./hack/update-infra-deployments.sh ../infra-deployments
      working-directory: cli

    - name: Checkout enterprise-contract-controller
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        repository: enterprise-contract/enterprise-contract-controller
        ref: main
        path: enterprise-contract-controller

    - name: Update enterprise-contract-controller
      run: ./hack/update-infra-deployments.sh ../infra-deployments
      working-directory: enterprise-contract-controller

    - name: Checkout ec-config
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        repository: conforma/config
        ref: main
        path: ec-config

    - name: Update ec-config
      env:
        GH_TOKEN: ${{ github.token }}
      run: ./hack/update-infra-deployments.sh ../infra-deployments
      working-directory: ec-config

    - name: Display diff
      run: git diff
      working-directory: infra-deployments

    - name: Checkout infra-deployments-ci
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        path: infra-deployments-ci

    - name: Create PR in infra-deployments
      env:
        EC_AUTOMATION_KEY: ${{ secrets.EC_AUTOMATION_KEY }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        APP_INSTALL_ID: ${{ vars.INFRA_DEPLOYMENTS_APP_INSTALL_ID }}
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset

        function createJWT() {
          local header=$(echo -n '{"alg":"RS256","typ":"JWT"}' | base64 | sed s/\+/-/ | sed -E s/=+$//)
          local now_utc=$(date --utc +%s)
          local payload=$(echo -n '{"iat":'$((now_utc - 60))',"exp":'$((now_utc + 120))',"iss":245286}' | base64 | sed s/\+/-/ | sed -E s/=+$//)
          local signature=$(echo -n "${header}.${payload}" | openssl dgst -sha256 -binary -sign <(echo "${EC_AUTOMATION_KEY}")| base64 | tr -d '\n=' | tr -- '+/' '-_')
          echo "${header}.${payload}.${signature}"
        }

        GITHUB_TOKEN=$(curl -s -X POST -H "Authorization: Bearer $(createJWT)" -H "Accept: application/vnd.github+json" "https://api.github.com/app/installations/${APP_INSTALL_ID}/access_tokens" | jq -r .token) \
        ./hack/create-pr.sh git@github.com:conforma/infra-deployments.git ../infra-deployments
      working-directory: infra-deployments-ci
